### ISSUE TITLE
Recipe for unknown cache name in html-webpack-plugin

### ISSUE THREAD

**Issue by binarykitchen** [mzgoddard/hard-source-webpack-plugin#177] opened 2017-09-26 09:11 UTC
Seeing this warning in conjunction with the html-webpack-plugin. Not sure what to do, what the recipe is?
Using your latest version here.

```
[hard-source:util] A child compiler (html-webpack-plugin for "index.html") has a memory cache but its cache name is unknown.
HardSourceWebpackPlugin will be disabled for this child compiler.   
```

the array of plugins is:

```js
  plugins: [
    // needed for displaying various info on dashboard like progress bar etc
    new DashboardPlugin(),

    // agressive caching for faster builds after first one
    new HardSourceWebpackPlugin(),

    new webpack.HotModuleReplacementPlugin(),

    // this plugin will cause the relative path of the module to be displayed
    new webpack.NamedModulesPlugin(),

    // generates an `index.html` file with the <script> injected.
    new HtmlWebpackPlugin({
      template: path.resolve(resourcesDir, 'index.html'),
      inject: true
    }),

    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
      minChunks: Infinity
    }),

    new FriendlyErrorsWebpackPlugin()
  ]
```

Any advice?

**Comment by jprivillaso** [comment] 2017-10-24 17:36
I am having the same issue and at first I thought that it was because I had the html-webpack-plugin in the webpack configuration, however even after deleting html-webpack-plugin the error still appears.

Need advice on this please

**Comment by milewski** [comment] 2017-10-27 11:01
same thing happening here .....

**Comment by Unforgiven-wanda** [comment] 2017-11-08 10:03
Basically the same issue as well

**Comment by piecyk** [comment] 2017-11-14 18:21
this commit fix the issue https://github.com/mzgoddard/hard-source-webpack-plugin/commit/18e5f637e9d455a13ffae38a7467af4764567cdf

awesome work @mzgoddard 👏

**Comment by mzgoddard** [comment] 2017-11-14 18:25
@piecyk thanks for confirming. Gonna close this issue then.

For anyone that stumbles on the this issue in the future and is curious: This was caused by a webpack 3 change that formalized how webpack child compiler's caches are stored. 18e5f63 updated hard-source to be able to support that change.

**Closed by mzgoddard** 2017-11-14 18:25 UTC
