### ISSUE TITLE
Encounter problems with huge modules.

### ISSUE THREAD

**Issue by bjmin** [mzgoddard/hard-source-webpack-plugin#182] opened 2017-10-17 02:33 UTC
i intend to use Hard Source to speed up build process, since my team had around 5000 modules. but it was not very optimistic after all, even could be much slower.

our stack includes coffee, ts and various style loaders or file loaders, and we are using HappyPack for reducing re-compile time. but after adding Hard Source, re-compile take much time before complete. will this cause some problems combined with Hard Source? i was wondering if there is anyone had same situation.

and every time we start webpack again, it produces lines of message
```
(node:2026) Warning: a promise was rejected with a non-error: [object Undefined]
```

could u provide some advice for our problems thx~

**Comment by bjmin** [comment] 2017-10-17 02:33
NODE version was 8, and we are not using DLL

**Comment by sontek** [comment] 2017-11-21 00:59
I get this error:

node: v8.9.1

we are using DLL

**Comment by platov** [comment] 2017-12-05 16:06
Have the same problem
node v6.12.0
no DLL
no HappyPack

The first build passes without warnings, next builds are with a lot of warnings.

**Comment by bjmin** [comment] 2017-12-06 03:34
looks like a reproducible issue
@mzgoddard could u give us some advice? thx~

**Comment by mzgoddard** [comment] 2017-12-11 06:57
@bjmin and others, best I know hard-source isn't causing the error itself.

```
(node:2026) Warning: a promise was rejected with a non-error: [object Undefined]
```

It's likely an interaction with one of the loaders or plugins in your project. Can you list the loaders and plugins used by your project or the build that has these errors? As well as the node, webpack, and hard-source-webpack-plugin versions? Any parts of your webpack config you can share would also help.

On slower rebuilds, make sure you don't have `require.context` or `require('./images/' + imageName '.png')` over a folder with lots of items (like node_modules lots) that are not built into your output (like a folder containing pngs and psds, while only the pngs are built). `hard-source` hashes the content of files recursively contained under a **context** module.

**Comment by platov** [comment] 2017-12-13 18:42
The warning
`Warning: a promise was rejected with a non-error: [object Undefined]`
appears as result of an error `Cannot read property '0' of undefined`
into the `webpack/lib/ContextModuleFactory.js` [Line 23](https://github.com/webpack/webpack/blob/c26d1f0d226ee9aa940211fa1b3822de7d09f4d5/lib/ContextModuleFactory.js#L23).

The `ContextModuleFactory.create` method accepts data(Object) parameter but String is passed from
https://github.com/mzgoddard/hard-source-webpack-plugin/blob/49ce9bd15f2dfb745ce0eee6070941f3598d05aa/lib/hard-context-module-factory.js#L63

So, possible, the problem is that the `factory.create` method calling with wrong parameters?
Should be like:
```javascript
factory.create({context, dependencies: [dependency]}, fn);
```

**Comment by mzgoddard** [comment] 2017-12-13 19:05
@platov interesting. This might be part of the module validation checking a dependency to an uncached ContextModule. I'll see if I can create a test case to reproduce.

https://github.com/mzgoddard/hard-source-webpack-plugin/blob/0a8296daeff4f5b582aba10147b94515b2760ad7/index.js#L985-L996

**Comment by mzgoddard** [comment] 2017-12-18 03:20
@bjmin @platov @sontek I was able to make a reproducible unit test in hard-source following @platov's narrowing down of the issue. Just published `0.5.9` with a fix for that.

**Comment by bjmin** [comment] 2017-12-18 08:27
@mzgoddard wow! sorry for being late! cheers

**Comment by platov** [comment] 2017-12-19 08:11
@mzgoddardI've tested it - Warnings now doesn't appear anymore. Thank you!

**Comment by mzgoddard** [comment] 2017-12-21 19:16
Awesome. Sounds like its working for folks. Closing.

**Closed by mzgoddard** 2017-12-21 19:16 UTC
