### ISSUE TITLE
Plugin breaks webpack bundling, while parsing cache

### ISSUE THREAD

**Issue by outOFFspace** [mzgoddard/hard-source-webpack-plugin#297] opened 2018-03-23 07:36 UTC
Sometimes, cache has invalid JSON, that breaks bundling. To solve this issue you should clear cached folder for yourself.  I propose to clear cache folder when JSON couldn't be parsed.

```
map.set(value.key, JSON.parse(
destBuffer.utf8Slice(0, value.size)
));
```

**Comment by outOFFspace** [comment] 2018-05-12 13:14
Any suggestions?

**Comment by mzgoddard** [comment] 2018-05-14 19:48
@outOFFspace I'm working on `0.7` (#319) for hard-source. And encounter this symptom. Though it was likely a different cause. (Hopefully it'll just fix it for you :wink:)

Most of the causes for this symptom are race conditions in the AppendSerializer (where this code is from). `0.7` or another version soon will switch to another cache storage package. `webpack-contrib`'s `cache-loader` uses a package (https://github.com/mzgoddard/hard-source-webpack-plugin/issues/287) that should do the job.

**Comment by outOFFspace** [comment] 2018-05-14 20:00
@mzgoddard thanks for reply. Looking forward for an update ;)

**Comment by mzgoddard** [comment] 2018-05-15 11:42
@outOFFspace Gave `cacache` a try and its much slower than the current other options (`append`, `leveldb`). I'm going to include it as a "safer" option in `0.7` and work towards a `append` 2.0.

I'll have the `cacache` option in soon but in the short interim you can give leveldb a shot.

```js
plugins: [
  new HardSourceWebpackPlugin(),
  new HardSourceWebpackPlugin.HardSourceLeveldbSerializerPlugin(),
]
```

The leveldb serializer is exposed already. You'll need to explicitly depend on leveldb. It should be "safer" than `append` but was removed as the default because it needs to build the leveldb binary to work.

You'll be able to use the `cacache` serializer the same way once I merge it in.

Here are some performance numbers with the current serializer and `cacache` (and why it won't become a new default).

**Comment by mzgoddard** [comment] 2018-05-17 14:36
@outOFFspace The new serializer plugin's I mentioned are now in `hard-source-webpack-plugin@next`. The default `append` has been replaced by `append-2` (internal libraries to hard-source). And `cacache` is available if you `npm install --save cacache` and use `new HardSourceWebpackPlugin.HardSourceCacacheSerializerPlugin()` in your plugins. I'd recommend trying `append-2` first, so just update hard-source to the `next` version. `cacache` is a safe but really slow option.

**Comment by mzgoddard** [comment] 2018-05-26 20:31
@outOFFspace Thank you for opening this issue. Moving away from the prior serializer I'm going to close this issue. Please open new issues for `append2`.

**Closed by mzgoddard** 2018-05-26 20:31 UTC
Labels: bug

**Comment by qasimalbaqali** [comment] 2019-04-04 16:20
Experiencing the same above issue as well
