### ISSUE TITLE
in second build the app not working

### ISSUE THREAD

**Issue by rzkhosroshahi** [mzgoddard/hard-source-webpack-plugin#472] opened 2018-11-26 12:00 UTC
### Expected Behavior

Hi after adding this plugin, improved my build time. but in the second build, the app doesn't work anyway and just throw an error that is `Uncaught SyntaxError: Unexpected token {` in your app.bundle.js 
and also another error:
`Provider.js:72 Uncaught ReferenceError: undefinedcreateProvider is not defined
    at Module.../node_modules/react-redux/es/components/Provider.js`

### Operating System, Node, and NPM dependency versions

```
Mac OS 10.14
Node 10.6.0

  "devDependencies": {
    "@babel/core": "^7.1.5",
    "@babel/plugin-proposal-class-properties": "^7.1.0",
    "@babel/plugin-proposal-decorators": "^7.1.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.1.0",
    "@babel/preset-env": "^7.1.5",
    "@babel/preset-react": "^7.0.0",
    "@babel/preset-typescript": "^7.1.0",
    "@babel/runtime": "^7.1.5",
    "@kamva/ui-kit": "^0.1.6",
    "@types/jest": "^22.2.3",
    "@types/react-redux": "^6.0.9",
    "awesome-typescript-loader": "^5.0.0",
    "axios": "^0.18.0",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^23.6.0",
    "babel-loader": "8.0.0",
    "babel-plugin-dynamic-import-node": "^2.1.0",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react-app-babel-7": "^4.0.2-0",
    "css-loader": "^0.28.11",
    "csstype": "^2.5.7",
    "dnd-core": "^4.0.5",
    "file-loader": "^1.1.11",
    "fork-ts-checker-notifier-webpack-plugin": "^0.6.2",
    "fork-ts-checker-webpack-plugin": "^0.4.9",
    "hard-source-webpack-plugin": "^0.12.0",
    "history": "^4.7.2",
    "husky": "^1.0.0-rc.13",
    "immutability-helper": "^2.8.1",
    "immutable": "^3.8.2",
    "jest": "^23.1.0",
    "lint-staged": "^7.2.0",
    "lodash": "^4.17.10",
    "node-sass": "^4.9.0",
    "prettier": "1.14.2",
    "raf": "^3.4.0",
    "react": "^16.5.2",
    "react-addons-test-utils": "^15.6.2",
    "react-dnd": "^5.0.0",
    "react-dnd-html5-backend": "^5.0.1",
    "react-dnd-test-backend": "^5.0.1",
    "react-dom": "^16.5.2",
    "react-hot-loader": "^4.3.11",
    "react-loadable": "^5.4.0",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-svg-font-icons": "^0.2.0",
    "react-testing-library": "^5.1.0",
    "redux": "^3.7.2",
    "redux-devtools": "^3.4.1",
    "redux-devtools-extension": "^2.13.2",
    "redux-immutable": "^4.0.0",
    "regenerator-runtime": "^0.12.1",
    "reselect": "^3.0.1",
    "sass-loader": "^7.0.3",
    "source-map-loader": "^0.2.3",
    "style-loader": "^0.21.0",
    "ts-jest": "^23.10.0",
    "ts-loader": "^5.2.1",
    "tslint": "^5.10.0",
    "tslint-config-prettier": "^1.15.0",
    "tslint-loader": "^3.6.0",
    "typesafe-actions": "^2.0.4",
    "typescript": "^3.0.3",
    "webpack": "^4.12.0",
    "webpack-cli": "^2.1.4",
    "webpack-serve": "^2.0.2"
  },
  "dependencies": {
    "@types/jwt-decode": "^2.2.1",
    "@types/react": "^16.3.14",
    "@types/react-loadable": "^5.4.0",
    "@types/react-router": "^4.0.32",
    "@types/react-router-dom": "^4.2.7",
    "chalk": "^2.4.1",
    "clean-webpack-plugin": "^0.1.19",
    "emotion": "^9.2.10",
    "express": "^4.16.3",
    "extract-text-webpack-plugin": "^4.0.0-beta.0",
    "html-webpack-plugin": "^3.2.0",
    "ip": "^1.1.5",
    "jwt-decode": "^2.2.0",
    "nodemon": "^1.17.5",
    "optimize-css-assets-webpack-plugin": "^4.0.2",
    "react-emotion": "^9.2.10",
    "react-frame-component": "^4.0.2",
    "react-helmet": "^5.2.0",
    "react-redux": "^5.0.7",
    "react-slick": "^0.23.2",
    "redux-saga": "^0.16.0",
    "tslint-webpack-plugin": "^1.2.2",
    "uglifyjs-webpack-plugin": "^1.2.5",
    "utility-types": "^2.1.0",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-merge": "^4.1.2",
    "webpack-serve-overlay": "^0.3.0"
  }
```

**Comment by xwjgo** [comment] 2018-11-26 14:46
I have the same problem...

**Comment by geirsagberg** [comment] 2018-11-27 12:44
Duplicate of #455 . Workaround is to roll back webpack to 4.19.0.

**Comment by kadamwhite** [comment] 2020-05-04 16:19
Closing as duplicate

**Closed by kadamwhite** 2020-05-04 16:19 UTC
